apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oxmux

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - sealed/sealed-oxmux-secret.yaml
  - sealed/sealed-ssh-keys.yaml

labels:
  - includeSelectors: false
    includeTemplates: false
    pairs:
      app.kubernetes.io/part-of: oxmux
